#!/usr/bin/env npx tsx

/**
 * PHASE_4_WHITE_PAPER Generator
 *
 * Converts PHASE_4_WHITE_PAPER.md from Echo Sound Lab into Paper Perfector Document schema.
 * Generates a TypeScript module that can be imported directly into App.tsx.
 */

import fs from 'fs';
import path from 'path';

interface Section {
  id: string;
  level: 1 | 2 | 3;
  title: string;
  body: string[];
  monoBlocks?: string[];
}

interface Document {
  title: string;
  subtitle?: string;
  metadata: Record<string, string>;
  sections: Section[];
}

// Helper function to slugify section titles into IDs
function slugify(text: string): string {
  return text.toLowerCase().replace(/[^\w\s-]/g, '').replace(/\s+/g, '-').substring(0, 50);
}

// Parse markdown into structured sections
function parseMarkdown(content: string): Section[] {
  const sections: Section[] = [];
  const lines = content.split('\n');

  let currentSection: Partial<Section> | null = null;
  let bodyLines: string[] = [];
  let monoBlock: string[] = [];
  let inCodeBlock = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // Detect code blocks
    if (line.startsWith('```')) {
      inCodeBlock = !inCodeBlock;
      if (inCodeBlock) {
        monoBlock = [];
      } else if (monoBlock.length > 0) {
        if (!currentSection?.monoBlocks) {
          currentSection!.monoBlocks = [];
        }
        currentSection!.monoBlocks.push(monoBlock.join('\n'));
        monoBlock = [];
      }
      continue;
    }

    if (inCodeBlock) {
      monoBlock.push(line);
      continue;
    }

    // Detect level-1 headers (# Title)
    if (line.startsWith('# ')) {
      // Save previous section
      if (currentSection && currentSection.title) {
        if (bodyLines.length > 0) {
          currentSection.body = bodyLines.filter(l => l.trim().length > 0);
        }
        sections.push(currentSection as Section);
      }

      const title = line.substring(2).trim();
      currentSection = {
        id: slugify(title),
        level: 1,
        title,
        body: []
      };
      bodyLines = [];
      continue;
    }

    // Detect level-2 headers (## Title)
    if (line.startsWith('## ')) {
      // Save previous section
      if (currentSection && currentSection.title) {
        if (bodyLines.length > 0) {
          currentSection.body = bodyLines.filter(l => l.trim().length > 0);
        }
        sections.push(currentSection as Section);
      }

      const title = line.substring(3).trim();
      currentSection = {
        id: slugify(title),
        level: 2,
        title,
        body: []
      };
      bodyLines = [];
      continue;
    }

    // Detect level-3 headers (### Title)
    if (line.startsWith('### ')) {
      // Save previous section
      if (currentSection && currentSection.title) {
        if (bodyLines.length > 0) {
          currentSection.body = bodyLines.filter(l => l.trim().length > 0);
        }
        sections.push(currentSection as Section);
      }

      const title = line.substring(4).trim();
      currentSection = {
        id: slugify(title),
        level: 3,
        title,
        body: []
      };
      bodyLines = [];
      continue;
    }

    // Accumulate body content
    if (currentSection) {
      bodyLines.push(line);
    }
  }

  // Save last section
  if (currentSection && currentSection.title) {
    if (bodyLines.length > 0) {
      currentSection.body = bodyLines.filter(l => l.trim().length > 0);
    }
    sections.push(currentSection as Section);
  }

  return sections;
}

async function main() {
  try {
    // Read the white paper
    const whitepaperPath = path.join(
      '/Users/DRA/Desktop/Echo Sound Lab/Echo Sound Lab v2.5',
      'PHASE_4_WHITE_PAPER.md'
    );

    console.log(`📖 Reading white paper from: ${whitepaperPath}`);
    const content = fs.readFileSync(whitepaperPath, 'utf-8');

    // Parse sections
    console.log('🔍 Parsing markdown...');
    const sections = parseMarkdown(content);
    console.log(`✅ Found ${sections.length} sections`);

    // Build document
    const document: Document = {
      title: 'Phase 4: In-Process Action Authority Architecture',
      subtitle: 'Echo Sound Lab - Regulator-Grade System Design',
      metadata: {
        'Project': 'Echo Sound Lab',
        'Phase': '4',
        'Status': 'Production-Ready',
        'Version': '1.0',
        'Date': new Date().toISOString().split('T')[0],
        'Classification': 'Architecture & Compliance'
      },
      sections
    };

    // Generate TypeScript module
    console.log('📝 Generating TypeScript module...');
    const typeScriptCode = `/**
 * PHASE_4_WHITE_PAPER Document
 *
 * Auto-generated by generatePhase4WhitePaper.ts
 * This document is ready for export to PDF via Paper Perfector.
 */

import type { Document } from "../models/DocumentSchema";

export const phase4WhitePaper: Document = ${JSON.stringify(document, null, 2)};
`;

    // Write output
    const outputPath = path.join(
      '/Users/DRA/Desktop/Paper Perfector/src/documents',
      'phase4WhitePaper.ts'
    );

    // Create documents directory if needed
    const docsDir = path.dirname(outputPath);
    if (!fs.existsSync(docsDir)) {
      fs.mkdirSync(docsDir, { recursive: true });
      console.log(`📁 Created documents directory: ${docsDir}`);
    }

    fs.writeFileSync(outputPath, typeScriptCode, 'utf-8');
    console.log(`\n✅ Document generated: ${outputPath}`);
    console.log(`\n📊 Statistics:`);
    console.log(`   - Sections: ${sections.length}`);
    console.log(`   - Metadata keys: ${Object.keys(document.metadata).length}`);

    const totalParagraphs = sections.reduce((sum, s) => sum + s.body.length, 0);
    const totalCodeBlocks = sections.reduce((sum, s) => sum + (s.monoBlocks?.length || 0), 0);
    console.log(`   - Paragraphs: ${totalParagraphs}`);
    console.log(`   - Code blocks: ${totalCodeBlocks}`);

    console.log(`\n🚀 Next steps:`);
    console.log(`   1. Update App.tsx to import the document:`);
    console.log(`      import { phase4WhitePaper } from "./documents/phase4WhitePaper";`);
    console.log(`   2. Replace the sampleDoc with phase4WhitePaper in the useState`);
    console.log(`   3. Start the dev server: npm run dev`);
    console.log(`   4. Click "Export PDF" to generate the final document`);

  } catch (error) {
    console.error('❌ Error:', error instanceof Error ? error.message : error);
    process.exit(1);
  }
}

main();
